# Generated by Django 6.0 on 2026-09-25 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_product_units_per_box'),
        ('orders', '0003_remove_order_bonus_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', 'Начальный остаток'), ('receipt', 'Приход'), ('expense', 'Ручной расход'), ('sale', 'Заказ сайта'), ('return', 'Отмена заказа'), ('reversal', 'Исправление')], max_length=16)),
                ('quantity', models.IntegerField(help_text='Изменение остатка в штуках со знаком')),
                ('units_per_box', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движения товаров',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['product', 'occurred_at'], name='inventory_s_product_060ca2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='stock_movement_nonzero'), models.CheckConstraint(condition=models.Q(('units_per_box__gte', 1)), name='stock_box_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='stock_price_nonnegative'), models.UniqueConstraint(condition=models.Q(('kind__in', ['sale', 'return'])), fields=('order', 'product', 'kind'), name='stock_order_once')],
            },
        ),
    ]
