# Generated by Django 6.0 on 2026-01-16 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_user_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCompromisedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromised_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен восстановления при взломе',
                'verbose_name_plural': 'Токены восстановления при взломе',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='users_accou_token_037110_idx'), models.Index(fields=['user', '-created_at'], name='users_accou_user_id_ab438c_idx')],
            },
        ),
    ]
