# Generated by Django 6.0 on 2026-01-16 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountcompromisedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_email', models.EmailField(max_length=254, verbose_name='Старый email')),
                ('new_email', models.EmailField(max_length=254, verbose_name='Новый email')),
                ('old_email_confirmed', models.BooleanField(default=False, verbose_name='Старый email подтвержден')),
                ('old_email_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения старого')),
                ('new_email_confirmed', models.BooleanField(default=False, verbose_name='Новый email подтвержден')),
                ('new_email_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения нового')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('can_cancel_until', models.DateTimeField(verbose_name='Можно отменить до')),
                ('status', models.CharField(choices=[('pending_old', 'Ожидает подтверждения старого email'), ('pending_new', 'Ожидает подтверждения нового email'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='pending_old', max_length=20, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('cancel_token', models.CharField(max_length=100, unique=True, verbose_name='Токен отмены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на смену email',
                'verbose_name_plural': 'Запросы на смену email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен')),
                ('email_type', models.CharField(choices=[('old', 'Старый email'), ('new', 'Новый email')], max_length=10, verbose_name='Тип email')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован в')),
                ('email_change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tokens', to='users.emailchangerequest', verbose_name='Запрос на смену')),
            ],
            options={
                'verbose_name': 'Токен подтверждения email',
                'verbose_name_plural': 'Токены подтверждения email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', '-created_at'], name='users_email_user_id_fd97b7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['status'], name='users_email_status_25d2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['cancel_token'], name='users_email_cancel__27bdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='emailconfirmationtoken',
            index=models.Index(fields=['token'], name='users_email_token_03bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailconfirmationtoken',
            index=models.Index(fields=['email_change_request', 'email_type'], name='users_email_email_c_ece4bb_idx'),
        ),
    ]
