# Generated by Django 6.0 on 2026-02-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bonus_discount_order_delivery_date_and_more'),
        ('users', '0004_emailchangerequest_emailconfirmationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс бонусов'),
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Начислено'), ('spent', 'Списано'), ('expired', 'Истекли'), ('refunded', 'Возвращено')], max_length=20, verbose_name='Тип транзакции')),
                ('amount', models.IntegerField(verbose_name='Количество бонусов')),
                ('balance_after', models.IntegerField(verbose_name='Баланс после операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция бонусов',
                'verbose_name_plural': 'Транзакции бонусов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_bonus_user_id_99a9b8_idx'), models.Index(fields=['transaction_type'], name='users_bonus_transac_089c6d_idx')],
            },
        ),
    ]
