# Generated by Django 6.0 on 2026-02-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bonus_balance_bonustransaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bonustransaction',
            name='users_bonus_user_id_99a9b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='bonustransaction',
            name='users_bonus_transac_089c6d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bonus_balance',
        ),
        migrations.DeleteModel(
            name='BonusTransaction',
        ),
    ]
