# Generated by Django 6.0 on 2026-02-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bonus_discount_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bonus_discount',
        ),
    ]
