# Generated by Django 6.0 on 2026-01-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country_of_origin',
        ),
        migrations.AddField(
            model_name='brand',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна бренда'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='hero/', verbose_name='Изображение'),
        ),
    ]
