# Generated by Django 6.0 on 2026-01-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_consultationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('new', 'Новинка'), ('hit', 'Хит продаж'), ('sale', 'Акция'), ('exclusive', 'Эксклюзив')], max_length=50, verbose_name='Лейбл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория оборудования'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='catalog_roo_slug_7fb099_idx'), models.Index(fields=['is_active', 'order'], name='catalog_roo_is_acti_a07ecb_idx')],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='rooms',
            field=models.ManyToManyField(blank=True, help_text='В каких помещениях используется эта категория', related_name='categories', to='catalog.room', verbose_name='Доступно для помещений'),
        ),
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.room', verbose_name='Помещение'),
        ),
    ]
