# Generated by Django 6.0 on 2026-01-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_category_parent_category_order_product_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, help_text='Счетчик заказов для сортировки по популярности', verbose_name='Количество заказов'),
        ),
    ]
