# Generated by Django 6.0 on 2026-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_orders_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-orders_count'], name='catalog_pro_orders__70eb76_idx'),
        ),
    ]
