# Generated by Django 6.0 on 2026-09-25 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_orders_count_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Штук в коробке'),
        ),
    ]
